language: java

jdk:
  - oraclejdk9
addons:
  apt:
    packages:
      - oracle-java9-installer

install: true

script: mvn clean verify

#after_success:
#  - bash <(curl -s https://codecov.io/bash)
#
#notifications:
#  email: false
