language: java

sudo: false
addons:
  apt:
    packages:
      - oracle-java7-installer

jdk:
  - oraclejdk7

install: true

script: mvn clean verify

#after_success:
#  - bash <(curl -s https://codecov.io/bash)
#
#notifications:
#  email: false
